# Generated by Django 4.0.4 on 2022-05-27 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pie_bank_app', '0003_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_user',
            fields=[
                ('Customer_id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('IFSC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Balance', models.IntegerField()),
            ],
        ),
    ]
