# Generated by Django 4.0.4 on 2022-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_bank_app', '0004_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_user',
            name='Balance',
            field=models.IntegerField(null=True),
        ),
    ]
