# Generated by Django 4.0.4 on 2022-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_bank_app', '0006_transction_alter_bank_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transction',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transction',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
