# Generated by Django 4.0.4 on 2022-05-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_bank_app', '0007_transction_date_transction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transction',
        ),
    ]
