# Generated by Django 4.0.4 on 2022-05-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_bank_app', '0009_transction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transction',
            old_name='Transction_from',
            new_name='Transaction_from',
        ),
        migrations.RenameField(
            model_name='transction',
            old_name='Transction_to',
            new_name='Transaction_to',
        ),
    ]
